language: node_js
node_js:
  - "8.12.0"
install: true

deploy:
  - provider: script
    skip_cleanup: true
    script: bash fake_deploy.sh $DEV_MESSAGE
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash fake_deploy.sh $MASTER_MESSAGE
    on:
      tags: true
      branch: master