language: node_js
node_js:
  - "8.12.0"
install: true

deploy:
  - provider: script
    script: bash fake_deploy.sh
    on:
      branch: develop
  - provider: script
    script: bash fake_deploy.sh
    on:
      tags: true
      branch: master